web:
  restart: always
  build: .
  container_name: mapping-slc
  command: npm start
  links:
   - db
  ports:
   - "3000:3000"
   - "5858:5858"
   - "35729:35729"
  environment:
   - NODE_ENV=development
  volumes:
   - ./:/opt/mapping-slc
   - /opt/mapping-slc/node_modules
   - /opt/mapping-slc/public
   - /opt/mapping-slc/uploads
db:
  image: mongo:3.2
  container_name: db_1
  restart: always
  ports:
   - "27017:27017"
  volumes:
   - db:/data/db
